language: java
jdk: oraclejdk8

sudo: required
dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DminimumPriority=1

after_success:
  - cd sentinel-dashboard
  - ls
  - docker build -t janyw/sentinel_dashboard:latest .
  - docker push janyw/sentinel_dashboard:latest

cache:
  directories:
  - $HOME/.m2/