language: java

sudo: required
dist: trusty

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DminimumPriority=1

after_success:
  - cd sentinel-dashboard
  - docker build -t janyw/sentinel-dashboard:latest .
  - docker push janyw/sentinel-dashboard:latest

cache:
  directories:
  - $HOME/.m2/
